# Generated by Django 3.2.12 on 2024-06-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana')], max_length=30)),
                ('currencyAmount', models.FloatField()),
                ('cryptoCurrency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana')], max_length=30)),
                ('cryptoAmount', models.FloatField()),
                ('cachedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyCode', models.CharField(max_length=20)),
                ('cryptoCurrency', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('change_24h', models.FloatField()),
                ('marketCap', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('trend', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
