# Generated by Django 3.2.12 on 2024-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_marketrate_trend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CachedData',
            new_name='CachedOfferData',
        ),
        migrations.RenameField(
            model_name='cachedofferdata',
            old_name='cachedDate',
            new_name='cacheDate',
        ),
        migrations.AddField(
            model_name='marketrate',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
